#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
FloTHERM HTML Report 对比验证脚本

对两个模型求解并对比 HTML Report，确认模型是否一致。

用法:
  # 对比两个模型文件 (自动求解)
  python compare_html_reports.py model_A.pdml model_B.pdml
  python compare_html_reports.py model_A.pack model_B.floxml

  # 直接对比已有的 HTML 报告 (跳过求解)
  python compare_html_reports.py report_A.html report_B.html

  # 指定 FloTHERM 路径
  python compare_html_reports.py A.pdml B.pdml --flotherm "path/to/flotherm.exe"

  # 指定容差
  python compare_html_reports.py A.pdml B.pdml --tolerance 0.1
"""

import os
import sys
import re
import subprocess
import argparse
import time
from pathlib import Path
from datetime import datetime
from html.parser import HTMLParser


# ---------------------------------------------------------------------------
# HTML Report Parser
# ---------------------------------------------------------------------------

class ReportData:
    """从 HTML 报告提取的结构化数据"""

    def __init__(self):
        self.project_name = ""
        self.generator = ""
        self.model_settings = {}      # modelling settings
        self.turbulence_settings = {}  # turbulence
        self.gravity_settings = {}     # gravity
        self.fluid = ""
        self.global_settings = {}      # pressure, ambient temp, etc.
        self.geometry = []             # list of dicts: {name, type, level, x, y, z, sx, sy, sz, collapsed, heat_spec, heat_applied}
        self.fixed_flows = []          # list of dicts
        self.overall_cutouts = []      # list of dicts
        self.temp_monitors = {}        # {name: final_temp}
        self.source_temps = {}         # {name: final_temp}
        self.convergence_iters = 0


def parse_html_report(html_path):
    """解析 FloTHERM HTML 报告，返回 ReportData"""
    if not Path(html_path).exists():
        return None, f"文件不存在: {html_path}"

    with open(html_path, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()

    data = ReportData()

    # --- Generator ---
    m = re.search(r'Generated By\s*</b>([^<]+)', content)
    if m:
        data.generator = m.group(1).strip()

    # --- Project Name ---
    m = re.search(r'Project Name\s*</b>\s*([^<]+)', content)
    if m:
        data.project_name = m.group(1).strip()

    # --- Model Settings ---
    model_section = re.search(
        r'Modelling Settings</b>(.*?)</p>\s*<p><b>Turbulence',
        content, re.DOTALL
    )
    if model_section:
        lines = model_section.group(1)
        settings = re.findall(r'\t(\S[^<]+)', lines)
        data.model_settings = {
            'flow_type': _nth(settings, 0, ''),
            'dimension': _nth(settings, 1, ''),
            'radiation': _nth(settings, 2, ''),
            'state': _nth(settings, 3, ''),
            'solar': _nth(settings, 4, ''),
        }

    # --- Turbulence ---
    turb_section = re.search(
        r'Turbulence Settings</b>(.*?)</p>\s*<p><b>Gravity',
        content, re.DOTALL
    )
    if turb_section:
        lines = turb_section.group(1)
        settings = re.findall(r'\t(\S[^<]+)', lines)
        data.turbulence_settings = {
            'type': _nth(settings, 0, ''),
            'model': _nth(settings, 1, ''),
        }

    # --- Gravity ---
    grav_section = re.search(
        r'Gravity Settings</b>(.*?)</p>\s*<p><b>(?:Project Fluid|Global)',
        content, re.DOTALL
    )
    if grav_section:
        lines = grav_section.group(1)
        settings = re.findall(r'\t(\S[^<]+)', lines)
        data.gravity_settings = {
            'type': _nth(settings, 0, ''),
            'direction': _nth(settings, 1, ''),
        }

    # --- Fluid ---
    m = re.search(r'Project Fluid\s*</b>\s*(\S+)', content)
    if m:
        data.fluid = m.group(1).strip()

    # --- Global Settings ---
    gm = re.search(r'Datum Pressure:\s*([\d.eE+-]+)\s*Pa', content)
    if gm:
        data.global_settings['datum_pressure'] = float(gm.group(1))
    gm = re.search(r'External Radiant Temperature:\s*([\d.]+)\s*degC', content)
    if gm:
        data.global_settings['ext_radiant_temp'] = float(gm.group(1))
    gm = re.search(r'External Ambient Temperature:\s*([\d.]+)\s*degC', content)
    if gm:
        data.global_settings['ext_ambient_temp'] = float(gm.group(1))

    # --- Geometry Table ---
    geo_section = re.search(
        r'Geometry Model\s*</font>(.*?)</table>',
        content, re.DOTALL
    )
    if geo_section:
        rows = re.findall(r'<tr>\s*(.*?)\s*</tr>', geo_section.group(1), re.DOTALL)
        for row in rows:
            cells = re.findall(r'<td[^>]*>\s*(.*?)\s*</td>', row, re.DOTALL)
            if len(cells) >= 12:
                entry = {
                    'name': _clean(cells[0]),
                    'type': _clean(cells[1]),
                    'level': _clean(cells[2]),
                    'x': _num(cells[3]),
                    'y': _num(cells[4]),
                    'z': _num(cells[5]),
                    'sx': _num(cells[6]),
                    'sy': _num(cells[7]),
                    'sz': _num(cells[8]),
                    'collapsed': _clean(cells[9]),
                    'heat_spec': _num(cells[10]),
                    'heat_applied': _num(cells[11]),
                }
                data.geometry.append(entry)

    # --- Fixed Flows ---
    ff_section = re.search(
        r'Fixed Flows\s*</font>.*?<table[^>]*>(.*?)</table>',
        content, re.DOTALL
    )
    if ff_section:
        rows = re.findall(r'<tr>\s*(.*?)\s*</tr>', ff_section.group(1), re.DOTALL)
        for row in rows:
            cells = re.findall(r'<td[^>]*>\s*(.*?)\s*</td>', row, re.DOTALL)
            if len(cells) >= 7 and 'Fixed Flows' not in cells[0]:
                data.fixed_flows.append({
                    'name': _clean(cells[0]),
                    'volume_flow': _num(cells[1]),
                    'mass_flow': _num(cells[2]),
                    'heat_flow': _num(cells[3]),
                    'direction': _clean(cells[4]),
                    'mean_temp': _num(cells[5]),
                    'max_temp': _num(cells[6]),
                })

    # --- Overall/Cutouts ---
    oc_section = re.search(
        r'Overall/Cutouts\s*</font>.*?<table[^>]*>(.*?)</table>',
        content, re.DOTALL
    )
    if oc_section:
        rows = re.findall(r'<tr>\s*(.*?)\s*</tr>', oc_section.group(1), re.DOTALL)
        for row in rows:
            cells = re.findall(r'<td[^>]*>\s*(.*?)\s*</td>', row, re.DOTALL)
            if len(cells) >= 15 and 'Domain' in cells[0]:
                data.overall_cutouts.append({
                    'name': _clean(cells[0]),
                    'face': _clean(cells[1]),
                    'max_solid_temp': _num(cells[-2]),
                    'mean_solid_temp': _num(cells[-1]),
                })

    # --- Temperature Monitor Summary (最终温度) ---
    tm_sections = re.split(r'Temperature Monitor Summary', content, flags=re.IGNORECASE)
    for section in tm_sections[1:]:
        header_match = re.search(
            r'<td[^>]*>\s*([^<]+?)\s*\n\s*\(degC\)', section
        )
        if header_match:
            monitor_name = header_match.group(1).strip()
            data_match = re.search(
                r'<tr>\s*<td[^>]*>\s*(\d+)\s*</td>\s*<td[^>]*>\s*([\d.eE+-]+)\s*</td>',
                section
            )
            if data_match:
                data.temp_monitors[monitor_name] = float(data_match.group(2))

    # --- Source Temperature (per-source per-iteration, 取最终迭代) ---
    # 找所有 Source Temperature 表格
    source_blocks = re.findall(
        r'Iteration Number\s*</td>\s*<td[^>]*>\s*Source Temperature\s*\(degC\)\s*</td>(.*?)</table>',
        content, re.DOTALL
    )
    for block in source_blocks:
        iter_rows = re.findall(
            r'<td[^>]*>\s*(\d+)\s*</td>\s*<td[^>]*>\s*([\d.eE+-]+)\s*</td>',
            block
        )
        if iter_rows:
            # 第一行是最高迭代 = 最终结果
            final_iter = int(iter_rows[0][0])
            final_temp = float(iter_rows[0][1])
            data.source_temps[f'Source_{len(data.source_temps)}'] = {
                'temp': final_temp,
                'iter': final_iter,
            }

    # --- Convergence: 最大迭代数 ---
    all_iters = re.findall(r'Iteration Number.*?<td[^>]*>\s*(\d+)\s*</td>', content)
    if all_iters:
        data.convergence_iters = max(int(x) for x in all_iters)

    return data, "OK"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _safe_print(text):
    """Safe print for Windows GBK console"""
    try:
        print(text)
    except UnicodeEncodeError:
        print(text.encode('gbk', errors='replace').decode('gbk'))

def _nth(lst, idx, default=''):
    return lst[idx] if idx < len(lst) else default


def _clean(s):
    """清理 HTML cell 内容"""
    return s.replace('&nbsp;', '').replace('\n', '').strip()


def _num(s):
    """尝试转数字，失败返回 None"""
    s = _clean(s)
    if not s:
        return None
    try:
        return float(s)
    except ValueError:
        return None


def _fmt(v):
    if v is None:
        return '-'
    if isinstance(v, float):
        return f'{v:.6g}'
    return str(v)


# ---------------------------------------------------------------------------
# FloTHERM Solver
# ---------------------------------------------------------------------------

DEFAULT_FLOTHERM = r"D:\Program Files\Siemens\SimcenterFlotherm\2504\WinXP\bin\flotherm.exe"


def solve_model(flotherm_exe, input_path, output_dir, label):
    """求解模型，返回 (html_path, success, elapsed)"""
    input_path = Path(input_path)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    output_pack = output_dir / f"{label}.pack"
    output_html = output_dir / f"{label}.html"

    cmd = [
        str(flotherm_exe),
        "-b",
        str(input_path),
        "-z", str(output_pack),
        "-r", str(output_html),
    ]

    _safe_print(f"  Solving: {input_path.name} -> {output_html.name}")
    start = time.time()
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
        elapsed = time.time() - start
        if result.returncode == 0 and (output_pack.exists() or output_html.exists()):
            _safe_print(f"  [OK] Solved ({elapsed:.0f}s)")
            return output_html, True, elapsed
        else:
            _safe_print(f"  [FAIL] rc={result.returncode}")
            if result.stderr:
                _safe_print(f"    {result.stderr[:300]}")
            return output_html, False, elapsed
    except subprocess.TimeoutExpired:
        elapsed = time.time() - start
        _safe_print(f"  [FAIL] Timeout ({elapsed:.0f}s)")
        return output_html, False, elapsed


# ---------------------------------------------------------------------------
# Comparison Logic
# ---------------------------------------------------------------------------

class DiffResult:
    def __init__(self):
        self.sections = []   # list of {section, items: [{key, val_a, val_b, match, diff}]}
        self.match_count = 0
        self.diff_count = 0
        self.missing_count = 0


def compare_data(data_a, data_b, tol=0.01):
    """对比两份 ReportData，返回 DiffResult"""
    diff = DiffResult()

    # 1. Model Settings
    section = {'section': '模型设置', 'items': []}
    for key in ['flow_type', 'dimension', 'radiation', 'state', 'solar']:
        va = data_a.model_settings.get(key, '')
        vb = data_b.model_settings.get(key, '')
        match = va == vb
        section['items'].append({
            'key': key, 'val_a': va, 'val_b': vb,
            'match': match, 'diff': '' if match else '不一致'
        })
    diff.sections.append(section)

    # 2. Turbulence & Gravity
    section = {'section': '湍流/重力', 'items': []}
    for key in ['type', 'model']:
        va = data_a.turbulence_settings.get(key, '')
        vb = data_b.turbulence_settings.get(key, '')
        match = va == vb
        section['items'].append({
            'key': f'turbulence_{key}', 'val_a': va, 'val_b': vb,
            'match': match, 'diff': '' if match else '不一致'
        })
    for key in ['type', 'direction']:
        va = data_a.gravity_settings.get(key, '')
        vb = data_b.gravity_settings.get(key, '')
        match = va == vb
        section['items'].append({
            'key': f'gravity_{key}', 'val_a': va, 'val_b': vb,
            'match': match, 'diff': '' if match else '不一致'
        })
    diff.sections.append(section)

    # 3. Fluid & Global Settings
    section = {'section': '流体/全局设置', 'items': []}
    match = data_a.fluid == data_b.fluid
    section['items'].append({
        'key': 'fluid', 'val_a': data_a.fluid, 'val_b': data_b.fluid,
        'match': match, 'diff': '' if match else '不一致'
    })
    for key in ['datum_pressure', 'ext_radiant_temp', 'ext_ambient_temp']:
        va = data_a.global_settings.get(key)
        vb = data_b.global_settings.get(key)
        match = _num_eq(va, vb, tol)
        d = '' if match else _num_diff(va, vb)
        section['items'].append({
            'key': key, 'val_a': _fmt(va), 'val_b': _fmt(vb),
            'match': match, 'diff': d
        })
    diff.sections.append(section)

    # 4. Geometry
    section = {'section': '几何结构', 'items': []}
    geo_a = {g['name']: g for g in data_a.geometry}
    geo_b = {g['name']: g for g in data_b.geometry}
    all_names = sorted(set(list(geo_a.keys()) + list(geo_b.keys())))
    for name in all_names:
        ga = geo_a.get(name)
        gb = geo_b.get(name)
        if ga and gb:
            for dim in ['x', 'y', 'z', 'sx', 'sy', 'sz', 'heat_spec', 'heat_applied']:
                va = ga.get(dim)
                vb = gb.get(dim)
                match = _num_eq(va, vb, tol)
                d = '' if match else _num_diff(va, vb)
                section['items'].append({
                    'key': f'{name}.{dim}', 'val_a': _fmt(va), 'val_b': _fmt(vb),
                    'match': match, 'diff': d
                })
        elif ga:
            section['items'].append({
                'key': name, 'val_a': '存在', 'val_b': '缺失',
                'match': False, 'diff': 'B 中缺失'
            })
        else:
            section['items'].append({
                'key': name, 'val_a': '缺失', 'val_b': '存在',
                'match': False, 'diff': 'A 中缺失'
            })
    diff.sections.append(section)

    # 5. Fixed Flows
    section = {'section': 'Fixed Flows', 'items': []}
    for i in range(max(len(data_a.fixed_flows), len(data_b.fixed_flows))):
        fa = _nth(data_a.fixed_flows, i)
        fb = _nth(data_b.fixed_flows, i)
        if fa and fb:
            for key in ['volume_flow', 'mass_flow', 'heat_flow', 'mean_temp', 'max_temp']:
                va = fa.get(key)
                vb = fb.get(key)
                match = _num_eq(va, vb, tol)
                d = '' if match else _num_diff(va, vb)
                section['items'].append({
                    'key': f'FixedFlow[{i}].{key}', 'val_a': _fmt(va), 'val_b': _fmt(vb),
                    'match': match, 'diff': d
                })
    diff.sections.append(section)

    # 6. Overall/Cutouts
    section = {'section': 'Overall/Cutouts', 'items': []}
    for i in range(max(len(data_a.overall_cutouts), len(data_b.overall_cutouts))):
        oa = _nth(data_a.overall_cutouts, i)
        ob = _nth(data_b.overall_cutouts, i)
        if oa and ob:
            for key in ['max_solid_temp', 'mean_solid_temp']:
                va = oa.get(key)
                vb = ob.get(key)
                match = _num_eq(va, vb, tol)
                d = '' if match else _num_diff(va, vb)
                label = f"{oa['name']}.{oa['face']}.{key}"
                section['items'].append({
                    'key': label, 'val_a': _fmt(va), 'val_b': _fmt(vb),
                    'match': match, 'diff': d
                })
    diff.sections.append(section)

    # 7. Temperature Monitors
    section = {'section': 'Temperature Monitor', 'items': []}
    all_monitors = sorted(set(
        list(data_a.temp_monitors.keys()) + list(data_b.temp_monitors.keys())
    ))
    for name in all_monitors:
        va = data_a.temp_monitors.get(name)
        vb = data_b.temp_monitors.get(name)
        match = _num_eq(va, vb, tol)
        d = '' if match else _num_diff(va, vb)
        section['items'].append({
            'key': name, 'val_a': _fmt(va), 'val_b': _fmt(vb),
            'match': match, 'diff': d
        })
    diff.sections.append(section)

    # 8. Source Temperatures
    section = {'section': 'Source Temperature', 'items': []}
    all_sources = sorted(set(
        list(data_a.source_temps.keys()) + list(data_b.source_temps.keys())
    ))
    for name in all_sources:
        sa = data_a.source_temps.get(name)
        sb = data_b.source_temps.get(name)
        if sa and sb:
            va = sa.get('temp')
            vb = sb.get('temp')
            match = _num_eq(va, vb, tol)
            d = '' if match else _num_diff(va, vb)
            section['items'].append({
                'key': name, 'val_a': _fmt(va), 'val_b': _fmt(vb),
                'match': match, 'diff': d
            })
    diff.sections.append(section)

    # 统计
    for sec in diff.sections:
        for item in sec['items']:
            if item['match']:
                diff.match_count += 1
            else:
                diff.diff_count += 1

    return diff


def _num_eq(a, b, tol=0.01):
    """比较两个数值是否在容差内相等"""
    if a is None and b is None:
        return True
    if a is None or b is None:
        return False
    if isinstance(a, str) or isinstance(b, str):
        return str(a) == str(b)
    return abs(float(a) - float(b)) <= tol


def _num_diff(a, b):
    if a is None or b is None:
        return 'N/A'
    try:
        return f'{abs(float(a) - float(b)):.6g}'
    except (ValueError, TypeError):
        return 'N/A'


# ---------------------------------------------------------------------------
# Report Output
# ---------------------------------------------------------------------------

def generate_diff_report(diff, label_a, label_b, output_path, tol):
    """生成 HTML 对比报告"""
    html = []
    html.append('<html><head><meta charset="utf-8">')
    html.append(f'<title>Model Comparison: {label_a} vs {label_b}</title>')
    html.append('<style>')
    html.append('body { font-family: "Microsoft YaHei", Arial, sans-serif; margin: 20px; font-size: 14px; }')
    html.append('table { border-collapse: collapse; width: 100%; margin: 10px 0; }')
    html.append('th, td { border: 1px solid #ddd; padding: 6px 10px; text-align: left; }')
    html.append('th { background-color: #2c3e50; color: white; }')
    html.append('tr:nth-child(even) { background-color: #f8f8f8; }')
    html.append('.pass { color: #27ae60; }')
    html.append('.fail { color: #e74c3c; font-weight: bold; }')
    html.append('.warn { color: #f39c12; }')
    html.append('.summary-box { background: #ecf0f1; padding: 15px; border-radius: 8px; margin: 15px 0; }')
    html.append('.section-title { background: #34495e; color: white; padding: 8px 12px; margin-top: 20px; }')
    html.append('.identical { background: #d5f5e3; padding: 15px; border-radius: 8px; margin: 15px 0; text-align: center; font-size: 18px; }')
    html.append('.different { background: #fadbd8; padding: 15px; border-radius: 8px; margin: 15px 0; text-align: center; font-size: 18px; }')
    html.append('</style></head><body>')

    html.append(f'<h1>模型对比验证报告</h1>')
    html.append(f'<p>生成时间: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>')
    html.append(f'<p>对比: <b>{label_a}</b> vs <b>{label_b}</b> | 数值容差: {tol}</p>')

    # 总结
    all_match = diff.diff_count == 0
    if all_match:
        html.append('<div class="identical">✓ 两个模型完全一致 — 所有项目匹配</div>')
    else:
        html.append(f'<div class="different">✗ 发现 {diff.diff_count} 处差异</div>')

    html.append(f'<div class="summary-box">')
    html.append(f'匹配: <b class="pass">{diff.match_count}</b> | ')
    html.append(f'差异: <b class="fail">{diff.diff_count}</b> | ')
    html.append(f'总计: {diff.match_count + diff.diff_count}')
    html.append(f'</div>')

    # 各 section 详情
    for sec in diff.sections:
        # section header
        fail_count = sum(1 for i in sec['items'] if not i['match'])
        if fail_count > 0:
            html.append(f'<div class="section-title">{sec["section"]} — <span class="fail">{fail_count} 处差异</span></div>')
        else:
            html.append(f'<div class="section-title">{sec["section"]} — <span class="pass">全部匹配</span></div>')

        html.append('<table>')
        html.append('<tr><th>项目</th><th>A</th><th>B</th><th>差异</th><th>状态</th></tr>')
        for item in sec['items']:
            status = '<span class="pass">✓</span>' if item['match'] else '<span class="fail">✗</span>'
            diff_val = item['diff'] if item['diff'] else ''
            diff_class = 'fail' if not item['match'] else ''
            html.append(
                f'<tr>'
                f'<td>{item["key"]}</td>'
                f'<td>{item["val_a"]}</td>'
                f'<td>{item["val_b"]}</td>'
                f'<td class="{diff_class}">{diff_val}</td>'
                f'<td>{status}</td>'
                f'</tr>'
            )
        html.append('</table>')

    html.append('</body></html>')

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(html))

    return all_match


def print_console_summary(diff, label_a, label_b):
    """控制台输出摘要"""
    _safe_print(f"\n{'='*60}")
    _safe_print(f"对比结果: {label_a} vs {label_b}")
    _safe_print(f"{'='*60}")

    for sec in diff.sections:
        fail_count = sum(1 for i in sec['items'] if not i['match'])
        status = "[OK] 全部匹配" if fail_count == 0 else f"[!!] {fail_count} 处差异"
        _safe_print(f"\n[{sec['section']}] {status}")
        for item in sec['items']:
            if not item['match']:
                _safe_print(f"  [X] {item['key']}: A={item['val_a']}  B={item['val_b']}  diff={item['diff']}")

    _safe_print(f"\n{'='*60}")
    if diff.diff_count == 0:
        _safe_print("结论: 两个模型完全一致")
    else:
        _safe_print(f"结论: 发现 {diff.diff_count} 处差异，请查看详细报告")
    _safe_print(f"{'='*60}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description='FloTHERM HTML Report 对比验证 — 求解两个模型并对比报告',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例:
  python compare_html_reports.py model_A.pdml model_B.pdml
  python compare_html_reports.py report_A.html report_B.html
  python compare_html_reports.py A.pdml B.floxml --tolerance 0.1
  python compare_html_reports.py A.pack B.pack --flotherm "C:/path/to/flotherm.exe"
        """
    )
    parser.add_argument('file_a', help='模型文件 A 或 HTML 报告 A')
    parser.add_argument('file_b', help='模型文件 B 或 HTML 报告 B')
    parser.add_argument('--flotherm', default=DEFAULT_FLOTHERM,
                        help='flotherm.exe 路径 (默认自动检测)')
    parser.add_argument('--tolerance', type=float, default=0.01,
                        help='数值对比容差 (默认 0.01)')
    parser.add_argument('-o', '--output', default=None,
                        help='对比报告输出路径 (默认 compare_result.html)')
    parser.add_argument('--output-dir', default=None,
                        help='求解输出目录 (默认 ./compare_output)')
    args = parser.parse_args()

    file_a = Path(args.file_a)
    file_b = Path(args.file_b)
    tol = args.tolerance

    if not file_a.exists():
        print(f"[FAIL] File not found: {file_a}")
        return 1
    if not file_b.exists():
        print(f"[FAIL] File not found: {file_b}")
        return 1

    is_html_a = file_a.suffix.lower() in ('.html', '.htm')
    is_html_b = file_b.suffix.lower() in ('.html', '.htm')

    # 确定 FloTHERM 路径
    flotherm_exe = Path(args.flotherm)
    if not is_html_a or not is_html_b:
        if not flotherm_exe.exists():
            # 尝试自动检测
            candidates = [
                r"D:\Program Files\Siemens\SimcenterFlotherm\2504\WinXP\bin\flotherm.exe",
                r"C:\Program Files\Siemens\SimcenterFlotherm\2504\WinXP\bin\flotherm.exe",
            ]
            for c in candidates:
                if Path(c).exists():
                    flotherm_exe = Path(c)
                    break
            else:
                print(f"[FAIL] flotherm.exe not found: {flotherm_exe}")
                print("  Use --flotherm to specify the path")
                return 1

    output_dir = Path(args.output_dir) if args.output_dir else Path('./compare_output')

    # --- 求解或直接使用 HTML ---
    if is_html_a:
        html_a = file_a
        label_a = file_a.stem
        _safe_print(f"A: Using existing report {file_a.name}")
    else:
        _safe_print(f"\n--- Solving Model A: {file_a.name} ---")
        html_a, ok_a, _ = solve_model(flotherm_exe, file_a, output_dir / 'a', 'model_a')
        label_a = file_a.stem
        if not ok_a and not html_a.exists():
            print(f"[FAIL] Model A solve failed, no report generated")
            return 1

    if is_html_b:
        html_b = file_b
        label_b = file_b.stem
        _safe_print(f"B: Using existing report {file_b.name}")
    else:
        _safe_print(f"\n--- Solving Model B: {file_b.name} ---")
        html_b, ok_b, _ = solve_model(flotherm_exe, file_b, output_dir / 'b', 'model_b')
        label_b = file_b.stem
        if not ok_b and not html_b.exists():
            print(f"[FAIL] Model B solve failed, no report generated")
            return 1

    # --- 解析 ---
    _safe_print(f"\n--- Parsing HTML Reports ---")
    data_a, status_a = parse_html_report(html_a)
    data_b, status_b = parse_html_report(html_b)

    if data_a is None:
        print(f"[FAIL] Parse error A: {status_a}")
        return 1
    if data_b is None:
        print(f"[FAIL] Parse error B: {status_b}")
        return 1

    _safe_print(f"A: {status_a} | Project={data_a.project_name} | Geometry={len(data_a.geometry)} | Monitors={len(data_a.temp_monitors)}")
    _safe_print(f"B: {status_b} | Project={data_b.project_name} | Geometry={len(data_b.geometry)} | Monitors={len(data_b.temp_monitors)}")

    # --- Compare ---
    _safe_print(f"\n--- Comparing (tolerance={tol}) ---")
    diff = compare_data(data_a, data_b, tol)

    # --- Output ---
    print_console_summary(diff, label_a, label_b)

    output_path = Path(args.output) if args.output else Path('compare_result.html')
    all_match = generate_diff_report(diff, label_a, label_b, output_path, tol)
    _safe_print(f"\nReport saved: {output_path}")

    return 0 if all_match else 1


if __name__ == '__main__':
    sys.exit(main())
