#!/usr/bin/env python3
"""
FloTHERM FloXML 导出工具

通过 FloSCRIPT 宏自动将 Pack/ECXML 文件导出为 FloXML 格式

功能:
    - 单文件导出 FloXML
    - 批量导出多个文件
    - 支持导出 Assembly 或 Project 级别的 FloXML

使用方法:
    # 单文件导出
    python export_floxml.py model.pack -o output.xml

    # 批量导出
    python export_floxml.py ./input_folder -o ./output_folder

    # 仅生成宏文件（不执行）
    python export_floxml.py model.pack -o output.xml --macro-only
"""

import os
import sys
import argparse
import subprocess
import tempfile
from pathlib import Path
from datetime import datetime
from typing import List, Optional, Tuple
import xml.etree.ElementTree as ET


class FloXMLExporter:
    """FloXML 导出器"""

    # 默认 FloTHERM 路径
    DEFAULT_FLOTHERM_PATHS = [
        r"C:\Program Files\Siemens\SimcenterFlotherm\2504\WinXP\bin\flotherm.exe",
        r"C:\Program Files\Siemens\SimcenterFlotherm\2020.2\WinXP\bin\flotherm.exe",
        r"C:\Program Files\Mentor Graphics\FloTHERM\V11\WinXP\bin\flotherm.exe",
    ]

    def __init__(self, flotherm_path: str = None):
        self.flotherm_path = flotherm_path or self._find_flotherm()

    def _find_flotherm(self) -> Optional[str]:
        """查找 FloTHERM 安装路径"""
        for path in self.DEFAULT_FLOTHERM_PATHS:
            if os.path.exists(path):
                return path
        return None

    def create_export_macro(self, input_file: str, output_file: str,
                            export_type: str = "project") -> str:
        """
        创建导出 FloXML 的 FloSCRIPT 宏

        Args:
            input_file: 输入文件路径 (Pack/ECXML)
            output_file: 输出 FloXML 路径
            export_type: 导出类型 ("project" 或 "assembly")

        Returns:
            宏文件路径
        """
        input_abs = os.path.abspath(input_file)
        output_abs = os.path.abspath(output_file)

        # 创建 FloSCRIPT 宏
        macro_content = f'''<?xml version="1.0" encoding="UTF-8"?>
<xml_log_file version="1.0">
    <!-- Auto-generated by export_floxml.py -->
    <project_open file="{input_abs}"/>
    <export_floxml file="{output_abs}"/>
    <project_close/>
</xml_log_file>
'''

        # 保存宏文件
        macro_path = output_abs.replace('.xml', '_macro.xml')
        with open(macro_path, 'w', encoding='utf-8') as f:
            f.write(macro_content)

        print(f"[INFO] 已创建宏文件: {macro_path}")
        return macro_path

    def create_batch_macro(self, input_files: List[str], output_dir: str) -> str:
        """
        创建批量导出宏

        Args:
            input_files: 输入文件列表
            output_dir: 输出目录

        Returns:
            宏文件路径
        """
        output_dir = os.path.abspath(output_dir)
        os.makedirs(output_dir, exist_ok=True)

        # 构建批量操作
        operations = []
        for input_file in input_files:
            input_abs = os.path.abspath(input_file)
            basename = Path(input_file).stem
            output_abs = os.path.join(output_dir, f"{basename}.xml")

            operations.append(f'''
    <!-- Export: {basename} -->
    <open file="{input_abs}"/>
    <export_floxml file="{output_abs}"/>
    <close/>''')

        macro_content = f'''<?xml version="1.0" encoding="UTF-8"?>
<FloSCRIPT version="1.0">
    <!-- Auto-generated batch export macro -->
    <!-- Generated at: {datetime.now().isoformat()} -->
    <!-- Total files: {len(input_files)} -->
{''.join(operations)}
</FloSCRIPT>
'''

        macro_path = os.path.join(output_dir, f"batch_export_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xml")
        with open(macro_path, 'w', encoding='utf-8') as f:
            f.write(macro_content)

        print(f"[INFO] 已创建批量宏文件: {macro_path}")
        print(f"[INFO] 包含 {len(input_files)} 个文件")
        return macro_path

    def run_macro(self, macro_path: str, wait: bool = True) -> bool:
        """
        运行 FloSCRIPT 宏

        Args:
            macro_path: 宏文件路径
            wait: 是否等待完成

        Returns:
            是否成功启动
        """
        if not self.flotherm_path:
            print("[ERROR] 未找到 FloTHERM 安装路径，请使用 --flotherm 参数指定")
            return False

        if not os.path.exists(self.flotherm_path):
            print(f"[ERROR] FloTHERM 路径不存在: {self.flotherm_path}")
            return False

        macro_abs = os.path.abspath(macro_path)

        # 构建命令
        # FloTHERM 运行宏的方式: flotherm -m macro.xml
        cmd = [self.flotherm_path, '-m', macro_abs]

        print(f"[INFO] 启动 FloTHERM...")
        print(f"[INFO] 命令: {' '.join(cmd)}")

        try:
            if wait:
                process = subprocess.run(cmd, capture_output=True, text=True)
                if process.returncode == 0:
                    print("[INFO] FloTHERM 执行完成")
                    return True
                else:
                    print(f"[ERROR] FloTHERM 执行失败: {process.stderr}")
                    return False
            else:
                subprocess.Popen(cmd)
                print("[INFO] FloTHERM 已在后台启动")
                return True

        except Exception as e:
            print(f"[ERROR] 启动 FloTHERM 失败: {e}")
            return False

    def export_single(self, input_file: str, output_file: str,
                      macro_only: bool = False) -> bool:
        """
        导出单个文件

        Args:
            input_file: 输入文件
            output_file: 输出文件
            macro_only: 仅生成宏文件

        Returns:
            是否成功
        """
        if not os.path.exists(input_file):
            print(f"[ERROR] 输入文件不存在: {input_file}")
            return False

        # 创建宏
        macro_path = self.create_export_macro(input_file, output_file)

        if macro_only:
            print(f"[INFO] 仅生成宏文件，不执行")
            print(f"[INFO] 请在 FloTHERM GUI 中运行宏: {macro_path}")
            return True

        # 执行宏
        return self.run_macro(macro_path)

    def export_batch(self, input_dir: str, output_dir: str,
                     macro_only: bool = False) -> Tuple[int, int]:
        """
        批量导出

        Args:
            input_dir: 输入目录
            output_dir: 输出目录
            macro_only: 仅生成宏文件

        Returns:
            (成功数, 总数)
        """
        input_path = Path(input_dir)
        if not input_path.exists():
            print(f"[ERROR] 输入目录不存在: {input_dir}")
            return 0, 0

        # 查找所有 Pack/ECXML 文件
        input_files = []
        for ext in ['*.pack', '*.Pack', '*.PACK',
                    '*.ecxml', '*.Ecxml', '*.ECXML']:
            input_files.extend(input_path.glob(ext))

        if not input_files:
            print(f"[WARN] 未找到 Pack/ECXML 文件: {input_dir}")
            return 0, 0

        input_files = [str(f) for f in input_files]
        print(f"[INFO] 找到 {len(input_files)} 个文件")

        # 创建批量宏
        macro_path = self.create_batch_macro(input_files, output_dir)

        if macro_only:
            print(f"[INFO] 仅生成宏文件，不执行")
            print(f"[INFO] 请在 FloTHERM GUI 中运行宏: {macro_path}")
            return len(input_files), len(input_files)

        # 执行宏
        if self.run_macro(macro_path):
            return len(input_files), len(input_files)
        else:
            return 0, len(input_files)


def create_simple_export_macro(input_file: str, output_file: str) -> str:
    """
    创建简单的导出宏（独立函数，供外部调用）

    Args:
        input_file: 输入 Pack/ECXML 文件
        output_file: 输出 FloXML 文件

    Returns:
        宏内容字符串
    """
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<xml_log_file version="1.0">
    <project_open file="{os.path.abspath(input_file)}"/>
    <export_floxml file="{os.path.abspath(output_file)}"/>
    <project_close/>
</xml_log_file>
'''


def main():
    parser = argparse.ArgumentParser(
        description='FloTHERM FloXML 导出工具',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
示例:
  # 单文件导出
  python export_floxml.py model.pack -o output.xml

  # 批量导出整个目录
  python export_floxml.py ./input_folder -o ./output_folder

  # 仅生成宏文件（手动在 GUI 中运行）
  python export_floxml.py model.pack -o output.xml --macro-only

  # 指定 FloTHERM 路径
  python export_floxml.py model.pack -o output.xml --flotherm "C:\\...\\flotherm.exe"
        '''
    )

    parser.add_argument('input', help='输入文件或目录 (Pack/ECXML)')
    parser.add_argument('-o', '--output', required=True, help='输出文件或目录')
    parser.add_argument('--flotherm', help='FloTHERM 可执行文件路径')
    parser.add_argument('--macro-only', action='store_true',
                       help='仅生成宏文件，不执行')
    parser.add_argument('--no-wait', action='store_true',
                       help='不等待 FloTHERM 完成')

    args = parser.parse_args()

    exporter = FloXMLExporter(flotherm_path=args.flotherm)

    # 判断是单文件还是目录
    if os.path.isfile(args.input):
        # 单文件导出
        success = exporter.export_single(
            args.input, args.output, macro_only=args.macro_only
        )
        sys.exit(0 if success else 1)
    else:
        # 批量导出
        success, total = exporter.export_batch(
            args.input, args.output, macro_only=args.macro_only
        )
        print(f"\n[完成] 成功: {success}/{total}")
        sys.exit(0 if success == total else 1)


if __name__ == '__main__':
    main()
