#!/usr/bin/env python3
"""
FloXML 生成器 - Python 版本

修复版：移除不支持的 solution_domain 元素
"""

import os


class FloXMLGenerator:
    """FloXML 生成器"""

    def __init__(self, model_name: str):
        self.model_name = model_name
        self.lines = []

    def _add(self, text: str, indent: int = 0):
        """添加一行"""
        self.lines.append("    " * indent + text)

    def write_header(self):
        """写入 XML 头部"""
        self._add('<?xml version="1.0" encoding="UTF-8" standalone="no" ?>')
        self._add('<xml_case>')

    def write_footer(self):
        """写入 XML 尾部"""
        self._add('</xml_case>')

    def add_name(self, name: str):
        """添加模型名称"""
        self._add(f'<name>{name}</name>')

    def start_attributes(self):
        """开始属性定义"""
        self._add('<attributes>')

    def end_attributes(self):
        """结束属性定义"""
        self._add('</attributes>')

    def add_material_isotropic(self, name: str, conductivity: float,
                                density: float = 1000, specific_heat: float = 1000):
        """添加各向同性材料"""
        if not any('<materials>' in line for line in self.lines):
            self._add('<materials>')

        self._add('<isotropic_material_att>')
        self._add(f'<name>{name}</name>', 1)
        self._add(f'<conductivity>{conductivity}</conductivity>', 1)
        self._add(f'<density>{density}</density>', 1)
        self._add(f'<specific_heat>{specific_heat}</specific_heat>', 1)
        self._add('</isotropic_material_att>')

    def end_materials(self):
        """结束材料定义"""
        self._add('</materials>')

    def add_thermal(self, name: str, power: float):
        """添加热源属性"""
        if not any('<thermals>' in line for line in self.lines):
            self._add('<thermals>')

        self._add('<thermal_att>')
        self._add(f'<name>{name}</name>', 1)
        self._add(f'<power>{power}</power>', 1)
        self._add('</thermal_att>')

    def end_thermals(self):
        """结束热源定义"""
        self._add('</thermals>')

    def start_geometry(self):
        """开始几何定义"""
        self._add('<geometry>')

    def end_geometry(self):
        """结束几何定义"""
        self._add('</geometry>')

    def add_cuboid(self, name: str, x: float, y: float, z: float,
                   dx: float, dy: float, dz: float,
                   material: str = None, thermal: str = None):
        """添加立方体"""
        self._add('<cuboid>')
        self._add(f'<name>{name}</name>', 1)
        self._add('<position>')
        self._add(f'<x>{x}</x>', 2)
        self._add(f'<y>{y}</y>', 2)
        self._add(f'<z>{z}</z>', 2)
        self._add('</position>')
        self._add('<size>')
        self._add(f'<x>{dx}</x>', 2)
        self._add(f'<y>{dy}</y>', 2)
        self._add(f'<z>{dz}</z>', 2)
        self._add('</size>')
        if material:
            self._add(f'<material>{material}</material>', 1)
        if thermal:
            self._add(f'<thermal>{thermal}</thermal>', 1)
        self._add('</cuboid>')

    def generate(self) -> str:
        """生成 XML 字符串"""
        return '\n'.join(self.lines)

    def save(self, filepath: str):
        """保存到文件"""
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(self.generate())
        print(f"[OK] FloXML 已保存到: {filepath}")


def create_simple_model():
    """创建一个简单的热仿真模型"""

    gen = FloXMLGenerator("Simple Heat Model")

    # 写入头部
    gen.write_header()
    gen.add_name("Simple Heat Model - Generated by Python")

    # 属性定义
    gen.start_attributes()

    # 添加材料
    gen.add_material_isotropic("Aluminum", conductivity=180, density=2700, specific_heat=900)
    gen.add_material_isotropic("FR4", conductivity=0.3, density=1200, specific_heat=880)
    gen.add_material_isotropic("Copper", conductivity=385, density=8930, specific_heat=385)
    gen.end_materials()

    # 添加热源
    gen.add_thermal("CPU_Power", power=15.0)
    gen.add_thermal("GPU_Power", power=10.0)
    gen.end_thermals()

    gen.end_attributes()

    # 几何定义
    gen.start_geometry()

    # PCB 板
    gen.add_cuboid("PCB", x=0, y=0, z=0, dx=0.1, dy=0.1, dz=0.002, material="FR4")

    # CPU
    gen.add_cuboid("CPU", x=0.03, y=0.03, z=0.002, dx=0.04, dy=0.04, dz=0.002,
                   material="Copper", thermal="CPU_Power")

    # GPU
    gen.add_cuboid("GPU", x=0.06, y=0.06, z=0.002, dx=0.03, dy=0.03, dz=0.001,
                   material="Copper", thermal="GPU_Power")

    # 散热器
    gen.add_cuboid("Heatsink", x=0.03, y=0.03, z=0.004, dx=0.05, dy=0.05, dz=0.01,
                   material="Aluminum")

    gen.end_geometry()

    # 写入尾部
    gen.write_footer()

    return gen


def main():
    """主函数"""
    print("=" * 60)
    print("FloXML 生成器 - Python 版本 (修复版)")
    print("=" * 60)

    # 创建模型
    gen = create_simple_model()

    # 保存文件
    output_path = r"D:\Program Files\Siemens\SimcenterFlotherm\2504\flotherm-automation\generated_model.xml"
    gen.save(output_path)

    # 显示内容
    print("\n生成的 FloXML 内容:")
    print("-" * 60)
    print(gen.generate())
    print("-" * 60)

    print(f"\n验证步骤:")
    print(f"1. 在 FloTHERM 中右键点击 Root Assembly")
    print(f"2. 选择 Import")
    print(f"3. 选择: {output_path}")


if __name__ == '__main__':
    main()
