#!/usr/bin/env python3
"""
FloXML 完整生成器 - 方式2

功能:
- 生成 Assembly FloXML (几何组件)
- 生成 Project FloXML (完整项目)

支持:
- 材料 (各向同性, 正交各向异性)
- 热源
- 立方体、圆柱体等几何
- 求解设置
- 网格设置
"""

import json
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Optional, Tuple


class FloXMLBuilder:
    """FloXML 构建器"""

    def __init__(self, name: str = "Model", floxml_type: str = "assembly"):
        """
        Args:
            name: 模型名称
            floxml_type: "assembly" 或 "project"
        """
        self.name = name
        self.floxml_type = floxml_type
        self.lines = []

        # 数据存储
        self.materials = []
        self.thermals = []
        self.surfaces = []
        self.geometry_objects = []

    def _add(self, text: str = "", indent: int = 0):
        """添加一行"""
        self.lines.append("    " * indent + text)

    # ==================== 通用方法 ====================

    def build(self) -> str:
        """构建完整 FloXML"""
        self.lines = []

        # Header
        self._add('<?xml version="1.0" encoding="UTF-8" standalone="no" ?>')
        self._add(f'<!-- Generated by Python FloXML Generator at {datetime.now().isoformat()} -->')
        self._add('<xml_case>')
        self._add(f'<name>{self.name}</name>')

        if self.floxml_type == "project":
            self._build_project_header()

        # Attributes
        self._build_attributes()

        # Geometry
        self._build_geometry()

        if self.floxml_type == "project":
            self._build_solution_domain()

        # Footer
        self._add('</xml_case>')

        return '\n'.join(self.lines)

    def save(self, filepath: str):
        """保存到文件"""
        content = self.build()
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"[OK] FloXML 已保存: {filepath}")
        return filepath

    # ==================== 材料方法 ====================

    def add_material_isotropic(self, name: str, conductivity: float,
                                density: float = 2700, specific_heat: float = 900):
        """添加各向同性材料"""
        self.materials.append({
            "type": "isotropic",
            "name": name,
            "conductivity": conductivity,
            "density": density,
            "specific_heat": specific_heat
        })

    def add_material_orthotropic(self, name: str, kx: float, ky: float, kz: float,
                                  density: float = 2700, specific_heat: float = 900):
        """添加正交各向异性材料"""
        self.materials.append({
            "type": "orthotropic",
            "name": name,
            "kx": kx, "ky": ky, "kz": kz,
            "density": density,
            "specific_heat": specific_heat
        })

    # ==================== 热源方法 ====================

    def add_thermal(self, name: str, power: float):
        """添加热源"""
        self.thermals.append({
            "name": name,
            "power": power
        })

    # ==================== 几何方法 ====================

    def add_cuboid(self, name: str, position: Tuple[float, float, float],
                   size: Tuple[float, float, float],
                   material: str = None, thermal: str = None):
        """添加立方体"""
        self.geometry_objects.append({
            "type": "cuboid",
            "name": name,
            "position": position,
            "size": size,
            "material": material,
            "thermal": thermal
        })

    # ==================== 内部构建方法 ====================

    def _build_project_header(self):
        """构建 Project FloXML 头部"""
        # Model settings
        self._add('<model>')
        self._add('<modeling>')
        self._add('<solution>flow_heat</solution>', 1)
        self._add('<radiation>off</radiation>', 1)
        self._add('<dimensionality>3d</dimensionality>', 1)
        self._add('<transient>false</transient>', 1)
        self._add('</modeling>')
        self._add('<gravity>')
        self._add('<type>normal</type>', 1)
        self._add('<normal_direction>neg_y</normal_direction>', 1)
        self._add('<gravity_value>9.81</gravity_value>', 1)
        self._add('</gravity>')
        self._add('<global>')
        self._add('<datum_pressure>101325</datum_pressure>', 1)
        self._add('<ambient_temperature>300</ambient_temperature>', 1)
        self._add('</global>')
        self._add('</model>')

        # Solve settings
        self._add('<solve>')
        self._add('<overall_control>')
        self._add('<outer_iterations>500</outer_iterations>', 1)
        self._add('</overall_control>')
        self._add('</solve>')

        # Grid settings
        self._add('<grid>')
        self._add('<system_grid>')
        self._add('<smoothing>true</smoothing>', 1)
        self._add('</system_grid>')
        self._add('</grid>')

    def _build_attributes(self):
        """构建属性部分"""
        self._add('<attributes>')

        # Materials
        if self.materials:
            self._add('<materials>', 1)
            for mat in self.materials:
                if mat["type"] == "isotropic":
                    self._add('<isotropic_material_att>', 2)
                    self._add(f'<name>{mat["name"]}</name>', 3)
                    self._add(f'<conductivity>{mat["conductivity"]}</conductivity>', 3)
                    self._add(f'<density>{mat["density"]}</density>', 3)
                    self._add(f'<specific_heat>{mat["specific_heat"]}</specific_heat>', 3)
                    self._add('</isotropic_material_att>', 2)
                elif mat["type"] == "orthotropic":
                    self._add('<orthotropic_material_att>', 2)
                    self._add(f'<name>{mat["name"]}</name>', 3)
                    self._add(f'<x_conductivity>{mat["kx"]}</x_conductivity>', 3)
                    self._add(f'<y_conductivity>{mat["ky"]}</y_conductivity>', 3)
                    self._add(f'<z_conductivity>{mat["kz"]}</z_conductivity>', 3)
                    self._add(f'<density>{mat["density"]}</density>', 3)
                    self._add(f'<specific_heat>{mat["specific_heat"]}</specific_heat>', 3)
                    self._add('</orthotropic_material_att>', 2)
            self._add('</materials>', 1)

        # Thermals
        if self.thermals:
            self._add('<thermals>', 1)
            for therm in self.thermals:
                self._add('<thermal_att>', 2)
                self._add(f'<name>{therm["name"]}</name>', 3)
                self._add(f'<power>{therm["power"]}</power>', 3)
                self._add('</thermal_att>', 2)
            self._add('</thermals>', 1)

        self._add('</attributes>')

    def _build_geometry(self):
        """构建几何部分"""
        self._add('<geometry>')

        for obj in self.geometry_objects:
            if obj["type"] == "cuboid":
                self._add('<cuboid>', 1)
                self._add(f'<name>{obj["name"]}</name>', 2)
                self._add('<position>', 2)
                self._add(f'<x>{obj["position"][0]}</x>', 3)
                self._add(f'<y>{obj["position"][1]}</y>', 3)
                self._add(f'<z>{obj["position"][2]}</z>', 3)
                self._add('</position>', 2)
                self._add('<size>', 2)
                self._add(f'<x>{obj["size"][0]}</x>', 3)
                self._add(f'<y>{obj["size"][1]}</y>', 3)
                self._add(f'<z>{obj["size"][2]}</z>', 3)
                self._add('</size>', 2)
                if obj.get("material"):
                    self._add(f'<material>{obj["material"]}</material>', 2)
                if obj.get("thermal"):
                    self._add(f'<thermal>{obj["thermal"]}</thermal>', 2)
                self._add('</cuboid>', 1)

        self._add('</geometry>')

    def _build_solution_domain(self):
        """构建求解域"""
        self._add('<solution_domain>')
        self._add('<position>', 1)
        self._add('<x>0</x>', 2)
        self._add('<y>0</y>', 2)
        self._add('<z>0</z>', 2)
        self._add('</position>', 1)
        self._add('<size>', 1)
        self._add('<x>1</x>', 2)
        self._add('<y>1</y>', 2)
        self._add('<z>1</z>', 2)
        self._add('</size>', 1)
        self._add('</solution_domain>')


# ==================== 便捷函数 ====================

def create_from_json(json_path: str, output_path: str) -> str:
    """从 JSON 文件创建 FloXML"""
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    floxml_type = data.get("type", "assembly")
    builder = FloXMLBuilder(data.get("name", "Model"), floxml_type)

    # 添加材料
    for mat in data.get("materials", []):
        if mat.get("type") == "Orthotropic":
            builder.add_material_orthotropic(
                mat["name"], mat["kx"], mat["ky"], mat["kz"]
            )
        else:
            builder.add_material_isotropic(
                mat["name"], mat.get("kx", mat.get("conductivity", 1))
            )

    # 添加热源
    for therm in data.get("thermals", []):
        builder.add_thermal(therm["name"], therm["power"])

    # 添加几何
    for geom in data.get("geometry", []):
        if geom["type"] == "cuboid":
            builder.add_cuboid(
                geom["name"],
                tuple(geom["position"]),
                tuple(geom["size"]),
                geom.get("material"),
                geom.get("thermal")
            )

    return builder.save(output_path)


def main():
    import argparse

    parser = argparse.ArgumentParser(description='FloXML Generator - Pure Python')
    parser.add_argument('--data', help='JSON data file')
    parser.add_argument('-o', '--output', required=True, help='Output path')
    parser.add_argument('--type', choices=['assembly', 'project'], default='assembly')

    args = parser.parse_args()

    if args.data:
        create_from_json(args.data, args.output)
    else:
        # 示例
        builder = FloXMLBuilder("Demo Model", args.type)
        builder.add_material_isotropic("Aluminum", 180)
        builder.add_material_isotropic("Copper", 385)
        builder.add_thermal("CPU_Heat", 15)
        builder.add_cuboid("CPU", (0, 0, 0), (0.04, 0.04, 0.002), "Copper", "CPU_Heat")
        builder.save(args.output)

    print(f"\nGenerated FloXML:")
    print("-" * 50)
    with open(args.output, 'r', encoding='utf-8') as f:
        print(f.read())


if __name__ == '__main__':
    main()
