#!/usr/bin/env python3
"""
FloXML 生成器 - 方式2：纯 Python

完全用 Python 模拟 VBA 逻辑生成 FloXML，不依赖 Excel

使用方法:
    # 使用 JSON 数据生成 FloXML
    python python_floxml_generator.py materials --data materials.json -o output.xml

    # 校验模式：与方式1生成的文件对比
    python python_floxml_generator.py verify --excel-output c:/temp/excel_output.xml --python-output python_output.xml
"""

import os
import sys
import json
from pathlib import Path
from typing import List, Dict, Optional
from datetime import datetime


class FloXMLBuilder:
    """FloXML 构建器 - 模拟官方 VBA 逻辑"""

    def __init__(self, model_name: str = "Model"):
        self.model_name = model_name
        self.lines = []
        self._materials = []
        self._thermals = []
        self._geometry_objects = []

    def _add(self, text: str, indent: int = 0):
        """添加一行"""
        self.lines.append("    " * indent + text)

    # ==================== Header ====================

    def write_header(self):
        """写入 XML 头部"""
        self._add('<?xml version="1.0" encoding="UTF-8" standalone="no" ?>')
        self._add(f'<!-- Generated by Python FloXML Generator at {datetime.now().isoformat()} -->')
        self._add('<xml_case>')

    def write_footer(self):
        """写入 XML 尾部"""
        self._add('</xml_case>')

    def add_name(self, name: str):
        """添加模型名称"""
        self._add(f'<name>{name}</name>')

    # ==================== Model Settings ====================

    def start_model(self, solution: str = "flow_heat", radiation: str = "off",
                    dimensionality: str = "3d", transient: bool = False):
        """开始模型设置"""
        self._add('<model>')
        self._add('<modeling>')
        self._add(f'<solution>{solution}</solution>', 1)
        self._add(f'<radiation>{radiation}</radiation>', 1)
        self._add(f'<dimensionality>{dimensionality}</dimensionality>', 1)
        self._add(f'<transient>{"true" if transient else "false"}</transient>', 1)
        self._add('</modeling>')

    def add_gravity(self, direction: str = "neg_y", value: float = 9.81):
        """添加重力设置"""
        self._add('<gravity>')
        self._add('<type>normal</type>', 1)
        self._add(f'<normal_direction>{direction}</normal_direction>', 1)
        self._add(f'<gravity_value>{value}</gravity_value>', 1)
        self._add('</gravity>')

    def add_global_settings(self, pressure: float = 101325, ambient_temp: float = 300):
        """添加全局设置"""
        self._add('<global>')
        self._add(f'<datum_pressure>{pressure}</datum_pressure>', 1)
        self._add(f'<ambient_temperature>{ambient_temp}</ambient_temperature>', 1)
        self._add('</global>')
        self._add('</model>')

    # ==================== Attributes ====================

    def start_attributes(self):
        """开始属性定义"""
        self._add('<attributes>')

    def end_attributes(self):
        """结束属性定义"""
        self._add('</attributes>')

    # Materials
    def add_material_isotropic(self, name: str, conductivity: float,
                                density: float = 1, specific_heat: float = 1):
        """添加各向同性材料"""
        if not any('<materials>' in line for line in self.lines):
            self._add('<materials>')

        self._add('<isotropic_material_att>')
        self._add(f'<name>{name}</name>', 1)
        self._add(f'<conductivity>{conductivity}</conductivity>', 1)
        self._add(f'<density>{density}</density>', 1)
        self._add(f'<specific_heat>{specific_heat}</specific_heat>', 1)
        self._add('</isotropic_material_att>')

        self._materials.append({"name": name, "type": "isotropic"})

    def add_material_orthotropic(self, name: str, kx: float, ky: float, kz: float,
                                  density: float = 1, specific_heat: float = 1):
        """添加正交各向异性材料"""
        if not any('<materials>' in line for line in self.lines):
            self._add('<materials>')

        self._add('<orthotropic_material_att>')
        self._add(f'<name>{name}</name>', 1)
        self._add(f'<conductivity_x>{kx}</conductivity_x>', 1)
        self._add(f'<conductivity_y>{ky}</conductivity_y>', 1)
        self._add(f'<conductivity_z>{kz}</conductivity_z>', 1)
        self._add(f'<density>{density}</density>', 1)
        self._add(f'<specific_heat>{specific_heat}</specific_heat>', 1)
        self._add('</orthotropic_material_att>')

        self._materials.append({"name": name, "type": "orthotropic"})

    def end_materials(self):
        """结束材料定义"""
        self._add('</materials>')

    # Thermals
    def add_thermal(self, name: str, power: float):
        """添加热源"""
        if not any('<thermals>' in line for line in self.lines):
            self._add('<thermals>')

        self._add('<thermal_att>')
        self._add(f'<name>{name}</name>', 1)
        self._add(f'<power>{power}</power>', 1)
        self._add('</thermal_att>')

        self._thermals.append({"name": name, "power": power})

    def end_thermals(self):
        """结束热源定义"""
        self._add('</thermals>')

    # ==================== Geometry ====================

    def start_geometry(self):
        """开始几何定义"""
        self._add('<geometry>')

    def end_geometry(self):
        """结束几何定义"""
        self._add('</geometry>')

    def add_cuboid(self, name: str, position: tuple, size: tuple,
                   material: str = None, thermal: str = None, active: bool = True):
        """添加立方体"""
        x, y, z = position
        dx, dy, dz = size

        self._add('<cuboid>')
        self._add(f'<name>{name}</name>', 1)
        self._add(f'<active>{"true" if active else "false"}</active>', 1)
        self._add('<position>')
        self._add(f'<x>{x}</x>', 2)
        self._add(f'<y>{y}</y>', 2)
        self._add(f'<z>{z}</z>', 2)
        self._add('</position>')
        self._add('<size>')
        self._add(f'<x>{dx}</x>', 2)
        self._add(f'<y>{dy}</y>', 2)
        self._add(f'<z>{dz}</z>', 2)
        self._add('</size>')
        self._add('<orientation>')
        self._add('<local_x><i>1</i><j>0</j><k>0</k></local_x>', 1)
        self._add('<local_y><i>0</i><j>1</j><k>0</k></local_y>', 1)
        self._add('<local_z><i>0</i><j>0</j><k>1</k></local_z>', 1)
        self._add('</orientation>')
        if material:
            self._add(f'<material>{material}</material>', 1)
        if thermal:
            self._add(f'<thermal>{thermal}</thermal>', 1)
        self._add('<localized_grid>false</localized_grid>', 1)
        self._add('</cuboid>')

        self._geometry_objects.append({"type": "cuboid", "name": name})

    # ==================== Solution Domain ====================

    def add_solution_domain(self, position: tuple, size: tuple):
        """添加求解域"""
        x, y, z = position
        dx, dy, dz = size

        self._add('<solution_domain>')
        self._add('<position>')
        self._add(f'<x>{x}</x>', 2)
        self._add(f'<y>{y}</y>', 2)
        self._add(f'<z>{z}</z>', 2)
        self._add('</position>')
        self._add('<size>')
        self._add(f'<x>{dx}</x>', 2)
        self._add(f'<y>{dy}</y>', 2)
        self._add(f'<z>{dz}</z>', 2)
        self._add('</size>')
        self._add('</solution_domain>')

    # ==================== Output ====================

    def generate(self) -> str:
        """生成 XML 字符串"""
        return '\n'.join(self.lines)

    def save(self, filepath: str):
        """保存到文件"""
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(self.generate())
        print(f"[OK] FloXML 已保存到: {filepath}")


def create_materials_floxml(materials: List[Dict], output_path: str) -> str:
    """
    从材料数据创建 FloXML

    Args:
        materials: 材料列表
        output_path: 输出路径

    Returns:
        生成的 FloXML 内容
    """
    builder = FloXMLBuilder("Materials")

    # Header
    builder.write_header()
    builder.add_name("Materials Export")

    # Attributes
    builder.start_attributes()

    for mat in materials:
        mat_type = mat.get("type", "Isotropic")

        if mat_type == "Orthotropic":
            builder.add_material_orthotropic(
                name=mat.get("name"),
                kx=mat.get("kx", 1),
                ky=mat.get("ky", 1),
                kz=mat.get("kz", 1)
            )
        elif mat_type == "Temperature Dependant":
            # 温度相关材料暂时用各向同性表示
            builder.add_material_isotropic(
                name=mat.get("name"),
                conductivity=mat.get("conductivity", 1)
            )
        else:
            builder.add_material_isotropic(
                name=mat.get("name"),
                conductivity=mat.get("kx", 1)
            )

    builder.end_materials()
    builder.end_attributes()

    # Footer
    builder.write_footer()

    # Save
    builder.save(output_path)

    return builder.generate()


def compare_floxml(file1: str, file2: str) -> Dict:
    """
    比较两个 FloXML 文件

    Returns:
        {
            "identical": True/False,
            "file1_materials": [...],
            "file2_materials": [...],
            "differences": [...]
        }
    """
    import xml.etree.ElementTree as ET

    def extract_materials(filepath):
        tree = ET.parse(filepath)
        root = tree.getroot()
        materials = []

        for mat in root.findall('.//isotropic_material_att'):
            name = mat.find('name')
            cond = mat.find('conductivity')
            materials.append({
                "name": name.text if name is not None else "",
                "conductivity": cond.text if cond is not None else ""
            })

        return materials

    mats1 = extract_materials(file1)
    mats2 = extract_materials(file2)

    differences = []

    # 比较
    if len(mats1) != len(mats2):
        differences.append(f"材料数量不同: {len(mats1)} vs {len(mats2)}")

    for m1, m2 in zip(mats1, mats2):
        if m1["name"] != m2["name"]:
            differences.append(f"材料名称不同: {m1['name']} vs {m2['name']}")
        if m1["conductivity"] != m2["conductivity"]:
            differences.append(f"导热系数不同 ({m1['name']}): {m1['conductivity']} vs {m2['conductivity']}")

    return {
        "identical": len(differences) == 0,
        "file1_materials": mats1,
        "file2_materials": mats2,
        "differences": differences
    }


def main():
    import argparse

    parser = argparse.ArgumentParser(
        description='FloXML 生成器 - 纯 Python',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
示例:
  # 从 JSON 生成 FloXML
  python python_floxml_generator.py materials --data materials.json -o output.xml

  # 比较两个 FloXML 文件
  python python_floxml_generator.py verify --file1 excel.xml --file2 python.xml
        '''
    )

    subparsers = parser.add_subparsers(dest='command', help='命令')

    # materials 命令
    mat_parser = subparsers.add_parser('materials', help='生成材料 FloXML')
    mat_parser.add_argument('--data', help='JSON 数据文件')
    mat_parser.add_argument('-o', '--output', required=True, help='输出路径')

    # verify 命令
    verify_parser = subparsers.add_parser('verify', help='比较两个 FloXML')
    verify_parser.add_argument('--file1', required=True, help='文件1 (Excel 生成)')
    verify_parser.add_argument('--file2', required=True, help='文件2 (Python 生成)')

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        return

    if args.command == 'materials':
        # 读取数据
        if args.data:
            with open(args.data, 'r', encoding='utf-8') as f:
                data = json.load(f)
                materials = data.get("materials", [])
        else:
            materials = [
                {"name": "Copper", "type": "Isotropic", "kx": 385},
                {"name": "FR4", "type": "Isotropic", "kx": 0.3},
                {"name": "Aluminum", "type": "Isotropic", "kx": 180},
            ]

        # 生成
        print("=" * 50)
        print("FloXML 生成器 - 方式2 (纯 Python)")
        print("=" * 50)

        content = create_materials_floxml(materials, args.output)

        print("\n生成的 FloXML 内容:")
        print("-" * 50)
        print(content)
        print("-" * 50)

    elif args.command == 'verify':
        # 比较
        print("=" * 50)
        print("FloXML 比较")
        print("=" * 50)

        result = compare_floxml(args.file1, args.file2)

        print(f"\n文件1 材料: {len(result['file1_materials'])} 个")
        print(f"文件2 材料: {len(result['file2_materials'])} 个")

        if result['identical']:
            print("\n[OK] 两个文件内容一致!")
        else:
            print("\n[DIFF] 发现差异:")
            for diff in result['differences']:
                print(f"  - {diff}")


if __name__ == '__main__':
    main()
